### ISSUE TITLE
Access Managment

### ISSUE THREAD

**Issue by strifel** [AlpakaInfraCrew/ansible#4]
- [uffd](https://git.cccv.de/uffd/uffd)
- [authentik](https://goauthentik.io)
- ~~[keykloak](#JUST-NOPE)~~ 😅
- [authelia](https://www.authelia.com/)

Anforderungen:
- LDAP Mimik
- oAuth2 (& präf. OpenID Connect)
- Gruppen Management & Gruppen Selbstverwaltung
- Zentrales Dashboard

**Comment by thies23** [comment]
patrull is deployed with uffd and the first systems are already part of uffd.
Onboarding of it-crew in progress
