### ISSUE TITLE
Pretalx

### ISSUE THREAD

**Issue by strifel** [AlpakaInfraCrew/ansible#9]

**Comment by thies23** [comment]
VM: klappa

**Comment by strifel** [comment]
Der Jugendbeirat würde sich über ein Pretalx in den nächsten Monaten freuen

**Comment by thies23** [comment]
@strifel wir haben immer noch die Interims Instanz, aber wenn du magst schreib gerne ne rolle dafür & roll aus :)

**Comment by strifel** [comment]
@td00 wollen wir Daten von dort umziehen?
Wenn ja: Kannst du mir einen dump senden?
